### ISSUE TITLE
2020 LTS Errors.

### ISSUE THREAD

**Issue by swirllyman** [Velorexe/UVNF#7]
Opened up the project on 2020.3.2f1 (Current LTS at the time of writing). Opened the ExampleScene from the UVNF - ExampleResources and am getting an error when running. Nothing proceeds to happen. Looks like it's failing to recognize the StartElement.

`NullReferenceException: Object reference not set to an instance of an object
UVNF.Entities.Containers.StoryGraph.ConnectStoryElements () (at Assets/UVNF/Scripts/Entities/Containers/StoryGraph.cs:79)
UVNF.Core.UVNFStoryManager.StartStory () (at Assets/UVNF/Scripts/Core/UVNFManager.cs:158)
UVNF.Core.UVNFStoryManager..ctor (UVNF.Entities.Containers.StoryGraph graph, UVNF.Core.UVNFManager manager, UVNF.Core.UI.UVNFCanvas canvas, System.Action afterStoryHandler) (at Assets/UVNF/Scripts/Core/UVNFManager.cs:127)
UVNF.Core.UVNFManager.StartStory (UVNF.Entities.Containers.StoryGraph graph) (at Assets/UVNF/Scripts/Core/UVNFManager.cs:49)
UVNF.Core.UVNFManager.Awake () (at Assets/UVNF/Scripts/Core/UVNFManager.cs:37)`

![Capture](https://user-images.githubusercontent.com/12868621/113815156-92f54b80-9727-11eb-8fad-244d4878bf3e.PNG)

Would be cool if you updated it, but if not no worries. Just thought I would let you know since it seems pretty robust.

**Comment by Velorexe** [comment]
Thanks for letting me know! I'll take a look at it right now.

**Comment by Velorexe** [comment]
There appeared to be a StartElement missing from the ExampleStory StoryGraph and some NullRefs that I overlooked. Those are fixed in the last PR into master.
I'm currently working on a revamp of UVNF which I hope will perform better!
